"""Known technical skills for regex-based job description extraction."""

KNOWN_SKILLS = [
    "python",
    "pytorch",
    "tensorflow",
    "jax",
    "scikit-learn",
    "sql",
    "spark",
    "kubernetes",
    "docker",
    "aws",
    "gcp",
    "azure",
    "mlops",
    "mlflow",
    "airflow",
    "dbt",
    "kafka",
    "langchain",
    "llamaindex",
    "rag",
    "vector database",
    "transformers",
    "hugging face",
    "fine-tuning",
    "rlhf",
    "computer vision",
    "opencv",
    "nlp",
    "llm",
    "deep learning",
    "reinforcement learning",
    "generative ai",
    "stable diffusion",
    "data engineering",
    "feature engineering",
    "a/b testing",
    "pandas",
    "numpy",
    "dask",
    "ray",
    "xgboost",
    "lightgbm",
    "catboost",
    "fastapi",
    "flask",
    "django",
    "react",
    "typescript",
    "java",
    "scala",
    "go",
    "rust",
    "c++",
    "cuda",
    "triton",
    "onnx",
    "kubeflow",
    "vertex ai",
    "sagemaker",
    "snowflake",
    "bigquery",
    "redshift",
    "postgres",
    "mongodb",
    "redis",
    "elasticsearch",
    "pinecone",
    "weaviate",
    "chromadb",
    "bert",
    "gpt",
    "diffusion",
    "neural network",
    "statistics",
    "bayesian",
    "time series",
    "forecasting",
    "anomaly detection",
    "recommendation systems",
    "search ranking",
    "information retrieval",
]
